[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]

[rpc_endpoints]
pentagon = "https://rpc.pentagon.games"

[etherscan]
pentagon = { key = "", url = "https://explorer.pentagon.games/api" }
